### ISSUE TITLE
Could you provide an example?

### ISSUE THREAD

**Issue by Naereen** [agronholm/sphinx-autodoc-typehints#10]
Hi.
Could you provide an example of a Python project documented using this extension?
It would help to see that it works in practice.
Kuddo for the project, kind regards.

**Comment by agronholm** [comment]
Every single project in the Asphalt framework uses it: https://github.com/asphalt-framework/

**Comment by Naereen** [comment]
I meant, adding one (or more) example(s) in the README.md file describing this project.

**Comment by agronholm** [comment]
I would much rather amend the documentation to answer any questions you have. Would that work for you?

**Comment by Naereen** [comment]
I don't have specific questions, I am not even using this extension. Sorry about the confusion.

I was just suggesting, as a general remark, that such repo will gain if it contained an example of use of this Sphinx extension. "Example of use" may be a link to a live documentation of some a Python project (e.g., ReadTheDocs) or some screenshots.
