### ISSUE TITLE
Doesn't strip annotations from the function signature for decorators

### ISSUE THREAD

**Issue by moi90** [agronholm/sphinx-autodoc-typehints#111]
I have a class:

```
class Output:
    def __init__(
        self, name: str, type: Optional[Type] = None, doc: Optional[str] = None
    ):
        ...
```

It is used as a decorator, therefore in my rst file, I reference it by `.. autodecorator:: Output`.

I would expect that sphinx-autodoc-typehints
 strips the annotations as advertised: `@morphocut.core.Output(name, type, doc)`

But instead I get `@morphocut.core.Output(name: str, type: Optional[Type] = None, doc: Optional[str] = None)`

**Comment by agronholm** [comment]
I cannot reproduce this, at least w/o sphinx-napoleon.

**Comment by agronholm** [comment]
You'll have to investigate this a bit deeper if you want me to make changes to this project.

**Comment by moi90** [comment]
I will try without napoleon. I tried to understand the code but had not enough time to find the cause for the behavior I was observing.

**Comment by agronholm** [comment]
If you can create a trivial project that exhibits this behavior then I can look at it and track the cause myself.

**Comment by moi90** [comment]
I'll try. In the meantime, this is the repository of my project: https://github.com/morphocut/morphocut/
The class is in morphocut/core.py, the corresponding documentation in docs/api.rst.

**Comment by agronholm** [comment]
This is what I got when building the docs on that project:
![decorator](https://user-images.githubusercontent.com/130003/67617524-95dad580-f7ec-11e9-861d-7ef176bc0fdf.png)
What's wrong with it?

**Comment by moi90** [comment]
Thanks for looking into this!

>  What's wrong with it?

I explicitly wrote `.. autodecorator:: Output(name, type, doc)` to circumvent the unwanted behavior and to get the desired output. If you just write `.. autodecorator:: Output`, the full signature with types is shown, something that I expected sphinx-autodoc-typehints to prevent.

**Comment by agronholm** [comment]
Okay, checking again.

**Comment by agronholm** [comment]
I was able to repro the problem so I'm investigating now.

**Comment by agronholm** [comment]
Ok, here is the gist of it is this: "what" is `decorator` but this case is not taken into consideration when the code tries to determine if we should be processing `__init__()` instead (which we should be). I'll have to fix the logic and add a test case for `autodecorator`.

**Comment by moi90** [comment]
Great, thanks for working on this!
