### ISSUE TITLE
Optional[Union[...]] doesn't preserve Optional hint

### ISSUE THREAD

**Issue by h1nk** [agronholm/sphinx-autodoc-typehints#115]
I noticed that `Optional` `Unions` like `Optional[Union[...]]` become simply `Union[..., None]`. While this is technically still correct I'd prefer for it to preserve the `Optional` type hint.

**Comment by agronholm** [comment]
Python itself does not preserve the `Optional`:
```
>>> a = Optional[str]
>>> a
typing.Union[str, NoneType]
```
So this is expected. If we were to support `Optional`, there would have to be an option that explicitly rendered such unions differently. This will have to be opt-in since otherwise I would get bug reports from people who declare their optionals explicitly as unions.

**Comment by h1nk** [comment]
Yes, an opt-in Sphinx configuration option exactly as you mentioned in your first comment is what I was thinking about. Personally I just prefer the readability of having the enclosing `Optional` around the `Union` in the generated documentation the same way it would appear in my source code style rather than evaluated `Union[..., None]`. I think an added option to enable this as a feature for those who want it would be great.

**Comment by agronholm** [comment]
I personally feel that the extra enclosure makes it _harder_ to read. But I will consider this.

**Comment by flying-sheep** [comment]
This is a trade-off between readability and clarity of intent: `Optional[Union[A, B]]` makes it clear that `None` is treated as a special case of “Calculate/use the default value” while `Union[A, B, None]` is simpler and easier to read as there’s less nesting.
