### ISSUE TITLE
Failure for generic classes with a "name" property

### ISSUE THREAD

**Issue by wouter-vdb** [agronholm/sphinx-autodoc-typehints#118]
When a generic class has a "name" property, a TypeError is raised:

```
tests/test_sphinx_autodoc_typehints.py:158: in test_format_annotation
    result = format_annotation(annotation)
sphinx_autodoc_typehints.py:119: in format_annotation
    args = get_annotation_args(annotation, module, class_name)
sphinx_autodoc_typehints.py:69: in get_annotation_args
    original = getattr(sys.modules[module], class_name)
E   TypeError: getattr(): attribute name must be string
```

This problem can be reproduced by replacing/adding the following for "class B" in `test_sphinx_autodoc_typehints.py`:

```
class B(Generic[T]):
    @property
    def name(self):
        return "B's name"
```

The problem is caused by the following condition on lines 44/45 in `sphinx_autodoc_typehints.py`:

```
    elif getattr(annotation, 'name', None):  # Required for at least Pattern
        return annotation.name
```

When the "B[T]" annotation is processed, this condition detects a 'name' and returns it. But this 'name' is actually a 'property' instance instead of a string, which causes the TypeError.

I use the following temporary "fix", but I'm not sure whether this is a "proper" fix.

```
    elif (getattr(annotation, 'name', None) and
          not isinstance(annotation.name, property):
        return annotation.name
```

**Comment by agronholm** [comment]
You're right, that is not a proper fix. This code path needs to be restricted to `typing` annotations.

**Comment by wouter-vdb** [comment]
Thank you for the swift fix.
