### ISSUE TITLE
Add option to inject "Return type" to "Returns" directive

### ISSUE THREAD

**Issue by mbanczerowski** [agronholm/sphinx-autodoc-typehints#126]
Hey! 
Thanks for excellent extension!

It would be nice to squeeze return type with common returns directive. (or maybe better to make it optional)

```python
def some_func(game_ids) -> int:
    """
    :return: game size in bytes
    """
```

Current:
![ee74a96393fd5716e7fc2f140a9f15f3](https://user-images.githubusercontent.com/56397676/72993733-2cbc2b80-3df6-11ea-85e8-2950dea1b7c2.png)

Expected:
![ee74a96393fd5716e7fc2f140a9f15f3 - Copy](https://user-images.githubusercontent.com/56397676/72993788-4493af80-3df6-11ea-9057-74ac92531009.png)

**Comment by agronholm** [comment]
I'm not in favor of this so I'm going to decline the request. It also kind of seems out of scope for this project so I'm going to decline. Sorry.

**Comment by mbanczerowski** [comment]
I see. Thanks for quick response

**Comment by Honno** [comment]
If anybody has an example of how they worked around this in their documentation solution, I'd love to know!
