### ISSUE TITLE
type hint comment support

### ISSUE THREAD

**Issue by gaborbernat** [agronholm/sphinx-autodoc-typehints#13]
this would allow using it under Python 2.7 :+1:

**Comment by agronholm** [comment]
Sorry. I will never, ever support Python 2.7 in any form.

**Comment by agronholm** [comment]
Not that I could anyway without some way of parsing the comments out of the source which would add another dimension of complexity to the project.

**Comment by gaborbernat** [comment]
This is not per se a Python 2.7 feature, that would be just the cherry on top. PEP-484 specifies type comments as valid Python 3.5+ feature, so that should be here for full type hint support.

**Comment by gaborbernat** [comment]
I'll have a look into it, and probably implement it afterwards..

**Comment by agronholm** [comment]
I won't promise to merge it, but if the code is simple I will at least consider.

**Comment by vitaly-krugl** [comment]
Any progress on this one? Is there another sphinx extension that supports type hint comments well? Many thanks!

**Comment by gaborbernat** [comment]
see https://pypi.org/project/sphinx-autodoc-types/ and https://github.com/gaborbernat/sphinx-autodoc-typehints

**Comment by madsmtm** [comment]
If I were to pick up what gaborbernat has worked in #17 and his forks, and extracted just the type comment support, would you consider merging? Or would it just not be worth it, when you consider that Python 2.7 has just a little over a year until it's [End Of Life](https://www.python.org/dev/peps/pep-0373/#update)

**Comment by gaborbernat** [comment]
To be fair there's a significant complication in my experience. I personally plan to instead rewrite this tool on top of mypy.

**Comment by untitaker** [comment]
I would also like to see this. As far as I can tell the way to do it nowadays would be to use the `typed_ast` package and `inspect.getsource`.

**Comment by untitaker** [comment]
I added basic support for this in #87, and it seems to work well enough for me.

**Comment by agronholm** [comment]
I feel that #87 implementing the parsing of those type comments is too much code to be added just to support a Python version that's going to be past its EOL in 5 months. How many people really need this?

**Comment by gaborbernat** [comment]
I would say quite a lot of people would really benefit from this. Sure in open source Python 2 is de facto dead after the end of the year. But there are still a lot of tools, distributions and corporate environments where Python 2 will long live after 2020. An even if your environment is not one like this if you plan to support those people stuck on these you will provide your type hints either as comments or stubs.

**Comment by agronholm** [comment]
I would be much more receptive for a PR that leverages another library for parsing the type comments.

**Comment by gaborbernat** [comment]
@untitaker you probably want to use https://github.com/Stewori/pytypes instead, that's what I've done. I created a PR a while back to add support via that here, but @agronholm rejected it so forked it and now is released via https://github.com/gaborbernat/sphinx-autodoc-typehints https://pypi.org/project/sphinx-autodoc-types/

**Comment by untitaker** [comment]
@agronholm after having removed support for the single-line version of type hint comments, the comments themselves do not need to be parsed. And extracting the comments from source is already done via an external lib.

**Comment by agronholm** [comment]
The reason I rejected @gaborbernat 's PR was because it made broad, unrelated changes to the project. If I were to receive another PR which added less code than @untitaker 's PR, I would – although reluctantly, allow this feature to be added.

**Comment by agronholm** [comment]
Is there really no library that has an enhanced version of `get_type_hints()` that supports type comments? That would be ideal.

**Comment by gaborbernat** [comment]
Nothing well maintained 👍 the pytypes kinda is your best choice out of a bad bunch.

**Comment by agronholm** [comment]
I take it that mypy does not have anything like that either...?

**Comment by gaborbernat** [comment]
mypy has no public API (other than stdout). And types extraction is multi-phase internal detail (read, resolve, etc - due to forward references and such).

**Comment by untitaker** [comment]
mypy uses typed_ast like my PR does while pytypes uses string methods to extract source comments. It doesn't matter to me that one has less loc than the other, I know which one I'd rather like to maintain.

**Comment by agronholm** [comment]
Given the lack of a better alternative, I will now review PR #17 today.

**Comment by gaborbernat** [comment]
@agronholm I think you wanted to say #87 😄

**Comment by agronholm** [comment]
Oops, fixed.

**Comment by untitaker** [comment]
Thanks for considering it. At least you can be sure that it will not regress for existing users because all the new code is effectively disabled if Python 3-style type annotations are used or if typed_ast is not installed.

**Comment by agronholm** [comment]
Yup – I forgot to look at it yesterday but I'll take care of it this weekend at least.
