### ISSUE TITLE
sphinx.util.inspect.Signature raises RemovedInSphinx40Warning

### ISSUE THREAD

**Issue by Balandat** [agronholm/sphinx-autodoc-typehints#133]
`sphinx.util.inspect.Signature` was deprecated in 2.4.0. Building docs in sphinx 3.0.0 with `sphinx-autodoc-typehints` therefore raises a ton of warnings of the following type:
```
RemovedInSphinx40Warning: sphinx.util.inspect.Signature() is deprecated
  warnings.warn('sphinx.util.inspect.Signature() is deprecated',
```

The dependency on `sphinx.util.inspect.Signature` should be removed, and instead the functionality from python's `inspect` module should be used.

**Comment by atagar** [comment]
Hi all. Until this is fixed you can suppress these warnings in your Sphinx conf.py with...

```
import warnings

warnings.filterwarnings('ignore', message = 'sphinx.util.inspect.Signature\(\) is deprecated')
```

**Comment by gaborbernat** [comment]
@agronholm can you please do a release with this? thanks!

**Comment by agronholm** [comment]
Yeah, I've been meaning to cut a release. There's a (warranted) flake8 failure which exposed a problem with the rendering of `NewType` and I couldn't yet figure out the correct way to do it. I'll try to get this over with real soon.

**Comment by gaborbernat** [comment]
Thanks 👍 looking forward to it.

**Comment by agronholm** [comment]
It's out now.

**Comment by gaborbernat** [comment]
Thanks!
