### ISSUE TITLE
Move `<local>` __qualname__ check

### ISSUE THREAD

**Issue by rmorshea** [agronholm/sphinx-autodoc-typehints#134]
Shouldn't this check:

https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L167-L171

Be moved into the body of this if statement?

https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L176-L191

It doesn't appear that qualname is used elsewhere in the function.

**Comment by rmorshea** [comment]
Not sure, but this change might resolve https://github.com/agronholm/sphinx-autodoc-typehints/issues/133

**Comment by agronholm** [comment]
No idea what the problem here is, so I'm closing this. The referenced issue has also been closed.

**Comment by rmorshea** [comment]
@agronholm I'm actually running into this again. What is the purpose of this warning? What can't be inferred about the type hints? My use case is a bit like this:

```python
def make_factory(cls, *args, **kwargs):
    def factory():
        """Factor for a class"""
        return cls(*args, **kwargs)
    return factory

my_debug_class = make_factory(MyClass, debug=1)
"""^ this is what's causing the problem"""
```

I'm assuming it would have something to do with the fact that you can't know what local values of a nested function are until runtime, but since Sphinx gathers docs at runtime, this limitation that you can't work with `<local>` functions doesn't make sense to me.

**Comment by agronholm** [comment]
AFAIK you can't make a Sphinx reference to a nested function, hence the warning.

Why not simply use `functools.partial()` instead of `make_factory()`?
