### ISSUE TITLE
Ref to type definition.

### ISSUE THREAD

**Issue by hound672** [agronholm/sphinx-autodoc-typehints#137]
Hello.
There is some class, e.g:
```
class SomeClass:
    def some_method(val: AnotherMyClass) -> None:
        pass
```
Is there a way to pass ref for `AnotherMyClass` in generated documentation?

**Comment by agronholm** [comment]
What do you mean? This is literally the one thing this plugin was made for.

**Comment by hound672** [comment]
For example:
1. class `SomeClass` in `some_class.py` file
2. class `AnotherMyClass` in `another_my_class.py` file
I'd like to get ref in generated documentation to definition of AnotherMyClass in `another_my_class.py` file

**Comment by agronholm** [comment]
This is what the plugin does by default. So what's the problem? I assume you have a docstring in the real-world equivalent of `some_method` and you have the `val` parameter documented.

**Comment by agronholm** [comment]
Closing due to requested information not being provided.
