### ISSUE TITLE
Support all parameter field names

### ISSUE THREAD

**Issue by adblair** [agronholm/sphinx-autodoc-typehints#144]
Sphinx [supports](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists) six different field names for parameter descriptions:

```
:param
:parameter
:arg
:argument
:key
:keyword
```

As far as I can tell, sphinx-autodoc-typehints only supports `:param`. Please could support be added for the other five?

**Comment by agronholm** [comment]
I was not able to support `:key` and `:keyword` because `:type` does not seem to affect them and this is how sphinx-autodoc-typehints adds that type information.

**Comment by adblair** [comment]
Great stuff, thank you!
