### ISSUE TITLE
New project maintainer wanted

### ISSUE THREAD

**Issue by agronholm** [agronholm/sphinx-autodoc-typehints#146]
I find myself spread too thin with my current projects to effectively fix the issues in this project. I'd love for someone to take over as maintainer.

**Comment by SebastianJL** [comment]
Hello

I am interested in helping. This would be my first contribution to open source as a maintainer. Can you elaborate a little bit what this would entail?

**Comment by agronholm** [comment]
You would be responsible for the continued development of this project. This means fixing bugs, dealing with pull requests and occasionally publishing new releases. I would ask you to keep the existing structure of the code base more or less the same and not make major changes without first checking with me.

Could you drop by Gitter so we could have a private chat?

**Comment by agronholm** [comment]
@gaborbernat is the new maintainer. Cheers!

**Comment by hoodmane** [comment]
This issue should probably be unpinned since it was resolved.
