### ISSUE TITLE
'None' is rendered differently to other type annotations.

### ISSUE THREAD

**Issue by domdfcoding** [agronholm/sphinx-autodoc-typehints#150]
Hi,

Currently type annotations of 'None' get converted to: 

```rest
``None``
```
 which Sphinx renders as code:

 
![image](https://user-images.githubusercontent.com/8050853/90153033-621f6b00-dd80-11ea-8f75-75803ddd7f7e.png)

This looks out of place when used alongside other type annotations. Instead, using:

```rest
:py:obj:`None`
```

gives a more consistent appearance, and provides a hyperlink to the Python documentation.

![image](https://user-images.githubusercontent.com/8050853/90153312-b75b7c80-dd80-11ea-9326-9e467bd2e573.png)

It's just a one-line change in the ``format_annotation`` function, so I'd be happy to submit a PR if you're interested in this change.

**Comment by agronholm** [comment]
Okay, go ahead.
