### ISSUE TITLE
How to keep type hints in signatures

### ISSUE THREAD

**Issue by trsvchn** [agronholm/sphinx-autodoc-typehints#156]
Hi! Thank you for this amazing extension!

I am using it with `napoleon`
```python
extensions = [
    "sphinx.ext.napoleon",
    'sphinx_autodoc_typehints',
]
napoleon_use_param = True
```

But in this configuration it removes original type hints from class, func, method signatures.

I would like to keep them as well. So, my question is, is there any option how to do that? A kind of parameter?

**Comment by agronholm** [comment]
There is no option currently for that.

**Comment by trsvchn** [comment]
> There is no option currently for that.

Thank you so much for a such quick response! Well... thank you anyway! Have a great day!
