### ISSUE TITLE
Disable logging on import for Sphinx documentation builds

### ISSUE THREAD

**Issue by ovaar** [agronholm/sphinx-autodoc-typehints#170]
**Describe the bug**
When Qcodes is imported in a python notebook which is build by sphinx, qcodes conditionally start logging.
The function `logger.running_in_test_or_tool` is evaluated after running `logger.start_logging_on_import` triggering the following error:
```
File "d:\git\qcodes\qcodes\logger\logger.py", line 365, in conditionally_start_all_logging
    if not running_in_test_or_tool() and start_logging_on_import():
File "d:\git\qcodes\qcodes\logger\logger.py", line 339, in start_logging_on_import
    config = qc.config
AttributeError: module 'qcodes' has no attribute 'config'
```

**To Reproduce**
Please provide a **minimal** reproducible example that developers can run to investigate the problem.
You can find help for creating such an example [here](https://stackoverflow.com/help/minimal-reproducible-example).

**Expected behavior**
sphinx should be added to the list of tools, therefore skipping `start_logging_on_import`

**Comment by agronholm** [comment]
Are you sure you created the ticket in the right project? None of this seems to be related to sphinx-autodoc-typehints.

**Comment by ovaar** [comment]
Your absolutely right, my bad.
Great piece of software by the way!
