### ISSUE TITLE
process_signature silently drops any docstring-specified signature

### ISSUE THREAD

**Issue by anntzer** [agronholm/sphinx-autodoc-typehints#20]
`process_signature` gets the argspec from the object itself, so any docstring-specified signature (http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autodoc_docstring_signature) gets silently dropped.

See e.g. http://defopt.readthedocs.io/en/stable/api.html#defopt.run vs https://github.com/evanunderscore/defopt/blob/a03769b931460ce9234c02351f4ee7fe9d055fee/defopt.py#L68 (defopt.run should be listed in the docs with the signature `run(funcs, *, parsers=None, short=None, show_types=False, argv=None)`).

Given that you can't necessarily afford to eval the annotations that may exist in a docstring-specified signature (and you actually want their string representations anyways), I guess a correct approach when such a signature is present (although a bit a pain to implement?) would be to parse the signature into an AST, fetch out the parts of the AST corresponding to the annotations, map them back to the string using the AST col_offset, and remove them thusly (and move them to the docstring).  Or perhaps there's some smarter approach...

**Comment by agronholm** [comment]
Is the intended use case builtin functions?

**Comment by anntzer** [comment]
The intended use case is the example linked, which is a project where the main codebase is still Py2/Py3 compatible (so there needs to be docstring-spoofed signatures for "simulated keyword-only arguments") but many new parts are not (so they can actually use Py3-only signatures, e.g. annotations).

It is obviously a rare use case; if you decide it's not worth supporting it, an explicit note stating that spoofed signatures will be unconditionally stripped out would still be helpful.

**Comment by agronholm** [comment]
If your project has polyglot code, why are you using this library in the first place? It's only useful with py3 type annotations.

**Comment by anntzer** [comment]
defopt's core is Py2 compatible (I am not the maintainer and it is thus not my choice), but many features are Py3-only.  So it makes sense to use sphinx-autodoc-typehints for the examples docs (http://defopt.readthedocs.io/en/stable/examples.html), which use annotations, but not for the main API docs (http://defopt.readthedocs.io/en/stable/api.html#defopt.run), which use docstring-spoofing.

**Comment by agronholm** [comment]
The problem is, there is no code in this project that would erase anything from the docstring. It only **adds** lines. So what do you suggest I should do?

**Comment by agronholm** [comment]
Hm, could `process_signature()` be the problem then?

**Comment by agronholm** [comment]
The correct approach would then be to make `process_signature()` a no-op when annotations are not present.

**Comment by agronholm** [comment]
@anntzer I am investigating this right now. Could you tell me what exactly is missing from the built docs so I can check whether my fix works?

**Comment by anntzer** [comment]
See https://github.com/evanunderscore/defopt/blob/master/defopt.py#L70 (result at http://defopt.readthedocs.io/en/latest/api.html#defopt.run).  Right now the docstring-signature is not correctly formatted as it is split over two lines, but upon joining the two lines into a single one, the result is that `run` is documented as taking `(*args, **kwargs)` and the docstring-signature does not appear anymore in the rendered docs.

**Comment by agronholm** [comment]
I just disabled sphinx-autodoc-typehints entirely and I still get that result. Do you not?

**Comment by anntzer** [comment]
Requoting myself:
> Right now the docstring-signature is not correctly formatted as it is split over two lines, but upon joining the two lines into a single one...

**Comment by agronholm** [comment]
Sorry for being so hard headed. But the problem should be gone now.

**Comment by anntzer** [comment]
Thanks!

**Comment by agronholm** [comment]
Could you verify that the whole thing works as intended? I will then make a new release.

**Comment by anntzer** [comment]
It does.

**Comment by agronholm** [comment]
Ok, v1.2.3 released.
