### ISSUE TITLE
:rtype: may end up joined to previous paragraph

### ISSUE THREAD

**Issue by bmerry** [agronholm/sphinx-autodoc-typehints#24]
If the last line of the incoming `lines` is part of an ordinary paragraph of text, then Sphinx treats the added `:rtype:` line as part of that paragraph and prints it as part of the text, instead of interpreting it. I've run into this when using `sphinx.ext.napoleon` (before `sphinx_autodoc_typehints`), with a `@property`. I don't know why Napoleon would be messing with property docstrings in this way, but it seems like it's potentially a wider problem (unless Sphinx makes any sort of guarantee about a trailing empty line).

I suggest that when `:rtype:` is appended (rather than inserted after a `:return:`), an empty line is added first. If you agree, I'm happy to write a PR.

**Comment by agronholm** [comment]
Please do write a PR, with tests now that there is a proper rendering test (``test_sphinx_output()``).

**Comment by agronholm** [comment]
Fixed in b198517f3154b6381be25224a3a661bd0ac93540.
