### ISSUE TITLE
Types created with NewType are rendered poorly.

### ISSUE THREAD

**Issue by bovlb** [agronholm/sphinx-autodoc-typehints#41]
If I have code like:
```
    Foo = typing.NewType('Foo', str)
    def bar(x: Foo):
        pass
```
then its parameter gets documented as:
```
    x (<function NewType.<locals>.new_type at 0x7f644b4c6488>)
```
I was expecting something like one of the following:
```
    x (Foo)
    x (Foo alias for str)
    x (str)
```

**Comment by thigm85** [comment]
I am having the same problem here :/

**Comment by okomestudio** [comment]
I'm having the same issue here. 

If the choice of output rendering is what's holding #45 back from being merged, my vote would probably be on `x (Foo)` in the examples above, as `x (Foo alias for str)` looks very verbose, which might defeat the purpose of aliasing, and `x (str)` does not look like it takes advantage of aliasing at all.

**Comment by exhuma** [comment]
@okomestudio I think it's good to leave the information about `str` in there somehow. How would someone read the docs know that passing a string is acceptable if that information is missing?

For example if you have code like:

    Foo = NewType('Foo', str)
    def foo(x: Foo) -> None:
        print(x)

Then it is legal to write:

    foo('hello world')

But if the docs only say that you can pass an instance of type `Foo`, then the reader of the docs has no clue that passing a `str` is also fine.
