### ISSUE TITLE
formatargspec is deprecated

### ISSUE THREAD

**Issue by frankier** [agronholm/sphinx-autodoc-typehints#51]
It's called here https://github.com/agronholm/sphinx-autodoc-typehints/blob/38ff0554bcf2d30b1886002be24deff59d665072/sphinx_autodoc_typehints.py#L163

The warning happens in Sphinx 2.x. It looks like this:

    .../lib/python3.6/site-packages/sphinx/ext/autodoc/inspector.py:117: RemovedInSphinx20Warning: formatargspec() is now deprecated.  Please use sphinx.util.inspect.Signature instead.
      RemovedInSphinx20Warning)

**Comment by agronholm** [comment]
Closed via 410958966cba3976444b0c1662409e5af000e21f.
