### ISSUE TITLE
Version 1.5.0 breaks with Sphinx<1.8

### ISSUE THREAD

**Issue by michelole** [agronholm/sphinx-autodoc-typehints#59]
The event `config-inited` was added on Sphinx 1.8 (https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-config-inited) and it's used by [sphinx_autodoc_typehints.py](https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L228).

However, sphinx_autodoc_typehints requires only [Sphinx>=1.7](https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/setup.cfg#L29).

Therefore, sphinx-autodoc-typehints 1.5.0 breaks with Sphinx<1.8, which is forced by e.g. `readthedocs.org`.

Should we bump the required Sphinx version or avoid the `config-inited` event?

See also https://github.com/agronholm/sphinx-autodoc-typehints/commit/2afccd39f9e559f4cbd593461080cdfede7c2d50#r31313681 for my inline comment.

**Comment by agronholm** [comment]
Seems like no matter what I do, things always break for *someone*. What am I supposed to do? Is there another event I could use?

**Comment by AlexandreDecan** [comment]
Would it be possible to make the code "aware" of the current version of Sphinx, so you can rely on ``config-inited`` if Sphinx >=1.8, and on the previous solution (if any) for Sphinx < 1.8 ?

**Comment by michelole** [comment]
> Seems like no matter what I do, things always break for _someone_. What am I supposed to do? Is there another event I could use?

Unfortunately I'm not a Sphinx developer, so I cannot answer that.

It seems to me the current code is wrong though, because it uses a Sphinx 1.8 event, but declares support for Sphinx >= 1.7.

> Would it be possible to make the code "aware" of the current version of Sphinx, so you can rely on `config-inited` if Sphinx >=1.8, and on the previous solution (if any) for Sphinx < 1.8 ?

I wonder if package managers like `pip` would automagically pick up e.g. `sphinx-autodoc-typehints=1.4.0` if sphinx-autodoc-typehints bumps up the minimum required Sphinx version?

**Comment by AlexandreDecan** [comment]
> It seems to me the current code is wrong though, because it uses a 
> Sphinx 1.8 event, but declares support for Sphinx >= 1.7.

Indeed, but requiring >=1.8 will lead to issues with readthedocs, right?

> I wonder if package managers like |pip| would automagically pick up e.g. 
> |sphinx-autodoc-typehints=1.4.0| if sphinx-autodoc-typehints bumps up 
> the minimum required Sphinx version?

I don't think so, but probably sphinx exposes its current version with something like ``sphinx.__version__``, so different code paths could be taken in function of its value?

**Comment by AlexandreDecan** [comment]
I quickly looked at Sphinx, and there's a variable that can be used to do version comparison: ``sphinx.version_info`` (see https://github.com/sphinx-doc/sphinx/blob/master/sphinx/__init__.py#L48).

**Comment by agronholm** [comment]
I used another event which should be available on all supported versions of Sphinx

**Comment by AlexandreDecan** [comment]
It works, thanks!
