### ISSUE TITLE
Option to leave type aliases as is

### ISSUE THREAD

**Issue by deep-fried-bacon** [agronholm/sphinx-autodoc-typehints#65]
I don't know whether this is doable, but I was wondering whether it would be possible to add an option to leave type aliases as is instead, of replacing them with the full definition.

for example
```
SomeTypeAlias = List[Union[str,int]]
def someFunc(someVar: SomeTypeAlias) : 
   """
        :param someVar:
   """
```

produces something like this:

**someFunc** (someVar)
    *Parameters:* **someVar** (List[Union[str,int]])
.
.

but I would like it to produce something like:

**someFunc** (someVar)
    *Parameters:* **someVar** (SomeTypeAlias)

optimally with a link for `SomeTypeAlias` to the definition

**Comment by agronholm** [comment]
Where would it get the type alias name?

**Comment by agronholm** [comment]
Moreover, how would the type alias help the developer understand what kind of types are allowed in the arguments?

**Comment by deep-fried-bacon** [comment]
Thank you for your responses.

So based on your question 'where would it get the type alias name', I'm assuming that this extension only looks at the autodoc signatures and docstrings and not the original code being documented. I hadn't realized that. One of the reasons I was asking this question is because I wasn't sure if it was possible or practical. 

That makes everything else kinda moot, but in case you're still curious: 

To your second question of why, the context I would be using this is primarily in documentation for myself and not for other developers. I find the length of some of the complete type information more confusing than a shorthand.

In contexts where documentation is being shared, length is still an issue, it's just usually overridden by the desire for the documentation to be readable without any background. However, for certain situations, it may still be worth having an alias that someone reading it would need learn, which is why having a link to the type definition would be really nice.

Thanks again

**Comment by agronholm** [comment]
Yes, without using heuristics with static code analysis, it is in fact impossible to determine if the annotation has been previously assigned to a variable somewhere.
