### ISSUE TITLE
Types are not linked

### ISSUE THREAD

**Issue by gnachman** [agronholm/sphinx-autodoc-typehints#69]
I ran into a problem where types to classes within my module are not linked in the HTML sphinx produces when I use sphinx-autodoc-typehints, but they are linked when I use `:type:` and `:rtype:`. I expect I'm doing something silly, but I've tried everything I can think of.

I have a minimal project here that demonstrates the problem: https://github.com/gnachman/typehintbug

See the `bar` module:

<img width="623" alt="screen shot 2018-12-26 at 8 30 49 pm" src="https://user-images.githubusercontent.com/427546/50465623-2df9fb00-094d-11e9-94a7-ad07c72f1424.png">

The types for the parameter and return value are not links.

When I dig into the source, I can see that the generated `:rtype:` is:

```
:rtype: :py:class:`~mything.foo.Foo`
```

This is where I'm stuck; the sphinx docs are not particularly helpful.

The `sphinx_autodoc_annotation` package produces proper links for my types, but I prefer `sphinx-autodoc-typehints` because it removes the type annotations from the documentation, which I find hard to read.

**Comment by agronholm** [comment]
How did you build the documentation for this project, exactly? There is no `setup.py` file and `make` doesn't do anything.

**Comment by agronholm** [comment]
There seem to be two problems here:
1. You're not declaring the modules (using `:mod:`mything.foo` etc.)
1. You're declaring the class as `mything.Foo` instead of its canonical name (`mything.foo.Foo`)

Once I made these changes, the link started working.
