### ISSUE TITLE
Cannot resolve forward reference in type annotations of ...

### ISSUE THREAD

**Issue by eblot** [agronholm/sphinx-autodoc-typehints#72]
Hi,

I'm not sure how to get rid of this warning, which happens with string annotated types,
*i.e.* `def foo(x: "Class")`:
  - setting `set_type_checking_flag` to `False` does not help
  - defining the partial or full module name does not help, *i.e.* `x: 'module.Class'` and `x: 'package.module.Class'` instead of `x: 'Class'`
 - I even tried relative module path syntax, *i.e.* `x: '.module.Class'` but this syntax does not seem valid.

How can I remove these warnings?
I'd like not to explicitly import a type only for type hinting documentation purpose, if possible.

Thanks.

**Comment by agronholm** [comment]
What warning are you seeing?

**Comment by agronholm** [comment]
[PEP 484](https://www.python.org/dev/peps/pep-0484/) contains an explanation for how the forward references work.

**Comment by agronholm** [comment]
Basically the forward references are Python expressions which, when evaluated at resolution time, must resolve to the actual type. Therefore you cannot avoid importing at least the module where the type can be found. That's just how this works.

**Comment by eblot** [comment]
Ok, my mistake. Thanks for the hint.

**Comment by agronholm** [comment]
> I'm not sure to get how this works with Sphinx and this extension though. How are evaluated the contents of the different files from the same package?

Sphinx looks up objects from its own internal inventory while `get_type_hints()` simply evaluates the expression in the string.

**Comment by agronholm** [comment]
If you really want to avoid importing the target classes then why are you using type annotations in the first place?

**Comment by eblot** [comment]
> If you really want to avoid importing the target classes then why are you using type annotations in the first place?

1. I can import target classes if it is required, although I do not really see the point of importing code implementation for the sake of declaring which kind of instance is used as a function argument (i.e. interface declaration vs. implementation). Anyway, if this is mandatory I'm ok with it, however:

2. I'm unable to find what to import when so that Sphinx extension does not complain about missing forward reference: if I try to import the missing class definitions, the code is no longer valid, because of the exact problem the forward reference syntax is expected to solve. I'm not sure how to proceed to debug this issue, which I guess can be summarised as: where should I import the missing classes definitions for Sphinx to find them?

**Comment by agronholm** [comment]
There is a section in the [README](https://github.com/agronholm/sphinx-autodoc-typehints#dealing-with-circular-imports) that explains how to deal with circular imports.

**Comment by eblot** [comment]
Ok, thanks a lot. 
"Import[ing] only the module, not the classes/functions from it" does the trick
