### ISSUE TITLE
support for properties

### ISSUE THREAD

**Issue by h-g-s** [agronholm/sphinx-autodoc-typehints#79]
Hi, I use properties in my code, e.g:

    @property
    def type(self) -> str:
        """variable type ('B') BINARY, ('C') CONTINUOUS and ('I') INTEGER"""
        return self.model.solver.var_get_type(self)

typehints includes 

Return type:   str

in the documentation.  Since this is a property, it not only *returns* a value. Would it be possible for the case of properties just to include the observation:

Type: str 

instead of the regular Returns xxx    text   ???

Thanks !!!!

**Comment by agronholm** [comment]
Perhaps this is not the right venue to ask for changes to core Sphinx behaviors?

**Comment by agronholm** [comment]
Perhaps I am wrong about this – I can take another look, but my initial thought was that Sphinx considers properties as methods.

**Comment by h-g-s** [comment]
Ok, I'll move my request to sphinx !  Thanks

**Comment by h-g-s** [comment]
Just moved this discussion to here
https://groups.google.com/d/msg/sphinx-users/ePvTuGxPr0U/L0aqVb_UAgAJ

If someone else has similar problems and would like to add something it would be great. Cheers, Haroldo
