### ISSUE TITLE
Adding automatic detection of return type

### ISSUE THREAD

**Issue by znicholls** [agronholm/sphinx-autodoc-typehints#80]
Hi there, 

Thanks for all your efforts on autodoc-typehints, it's super useful!

As I understand it, for a docstring like the below, autodoc-typehints would not currently automatically include the type of the output in the 'Returns' section but would automatically include the return type for the `starting_point` argument in the 'Parameters' section.

```python
def my_func(starting_point: str) -> str:
    """
    Convert string to my special logic
    
    Parameters
    -----------
    starting_point
        String to start with

    Returns
    --------
        Output converted to a new string with my custom algorithm
    """
    return starting_point.lower().replace("a", "B")
```

I was wondering:

- whether this is on purpose?
- how hard you think it would be to add the ability to include the return type automatically to autodoc-typehints?
    - I'm happy to have a go at implementing, I just want to have a sense of whether you think it would be a 1hr job or a 10hr job so I have a sense of what I might be up against

Cheers again

**Comment by agronholm** [comment]
The return type does not get added because you don't have a `:return:` or `:returns` in your docstring. I don't remember my reasoning for this, but you can find the relevant code [here](https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L216-L222).

**Comment by agronholm** [comment]
Is there a reason why you're not using the standard Sphinx markup for parameter annotations?

**Comment by znicholls** [comment]
> The return type does not get added because you don't have a `:return:` or `:returns` in your docstring

Ah yes of course. I think I just need to use `napoleon_use_rtype=False` and then it should appear. I'll have a go and let you know.

> Is there a reason why you're not using the standard Sphinx markup for parameter annotations?

I find it really hard to read and match prefer the [numpy style docstrings](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html).

**Comment by znicholls** [comment]
In any case this isn't an issue with autodoc-typehints so I'll close
