### ISSUE TITLE
Title-casing annotation classes breaks on e.g. AsyncIterator

### ISSUE THREAD

**Issue by oremanj** [agronholm/sphinx-autodoc-typehints#81]
In Python 3.7 (https://github.com/agronholm/sphinx-autodoc-typehints/commit/a09b018bf54d5a7eabd853043e9a30a4147cdc9d), the `__origin__` of `typing.List[T]` is just `list`. It looks like you're converting this to `List` using `str.title()`: https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L115

But this breaks multi-word type hints: `typing.AsyncIterator` becomes `typing.Asynciterator`, which creates a broken reference.

**Comment by wkschwartz** [comment]
I've run into this as well

**Comment by agronholm** [comment]
Fixed in 3c9f4f38.
