### ISSUE TITLE
Consider using typing_inspect

### ISSUE THREAD

**Issue by oremanj** [agronholm/sphinx-autodoc-typehints#82]
There's now a `typing_inspect` package on PyPI so you don't have to inspect all the type hint `__attributes__` yourself: https://github.com/ilevkivskyi/typing_inspect

I haven't investigated in detail, but maybe it could improve the simplicity and correctness of this package?

**Comment by untitaker** [comment]
I don't think this package would provide a lot. It seems to mostly contain functions to inspect the types once you have them, but that's not what the sphinx plugin does anyways.

**Comment by agronholm** [comment]
This looks like something that could be useful for my other project, [typeguard](https://pypi.org/project/typeguard/).

**Comment by agronholm** [comment]
Unfortunately typing_inspect only works with the latest version of `typing` and does not support `typing_extensions`, making it useless to me.
