### ISSUE TITLE
Effective default for `set_type_checking_flag` option

### ISSUE THREAD

**Issue by erikkemperman** [agronholm/sphinx-autodoc-typehints#84]
Hi,

The readme says the default for the `set_type_checking_flag` option is `True`:

https://github.com/agronholm/sphinx-autodoc-typehints/blob/ae9c54acd9c34242441a019bf19451bf67d712f5/README.rst#L58-L59

However, the effective default set in the code is `False`:

https://github.com/agronholm/sphinx-autodoc-typehints/blob/ae9c54acd9c34242441a019bf19451bf67d712f5/sphinx_autodoc_typehints.py#L246

So I was just wondering, which should it be?

Thanks for a great piece of work, by the way 👍

**Comment by agronholm** [comment]
The discrepancy has been fixed in ea992d8f.
