### ISSUE TITLE
General annotations shows default arguments

### ISSUE THREAD

**Issue by UncleGoogle** [agronholm/sphinx-autodoc-typehints#86]
`typing.Dict` without specifiers (like `typing.Dict[str, str]`) shouldn't display strange output (see img attached). The same `typing.List` ect.

```python
def func() -> typing.Dict
```
output:

[![Screenshot from Gyazo](https://gyazo.com/3d4ec5baca6e72eaccbf09960f507964/raw)](https://gyazo.com/3d4ec5baca6e72eaccbf09960f507964)

Expected result

- `Dict`

Workaround:

```python
def fun() -> `dict`
```

But it should be consistent across the docs that the uppercase letter is shown everywhere if someone uses also not general annotations

**Comment by agronholm** [comment]
I'd very much like to get this fixed but alas, I don't think I can fit it into the next immediate release.
