### ISSUE TITLE
Option to write out types even when params are undocumented

### ISSUE THREAD

**Issue by untitaker** [agronholm/sphinx-autodoc-typehints#88]
Our library has more type hints than actual/manual documentation. It would be nice if we could put the types in the docs to give the user *something* even if our params are not documented. The way I would imagine this is that this extension adds a placeholder `:param foo:` if it's missing.

If you accept this feature request I would start implementing it.

**Comment by untitaker** [comment]
@agronholm do you have an opinion on this?

**Comment by agronholm** [comment]
I'm sort of leaning towards accepting this. It's trivial to change but I'm unsure if I should enable it by default.

**Comment by untitaker** [comment]
That's okay, if it's behind a flag that works for me as well

**Comment by agronholm** [comment]
Ok, let's say we make this opt-in and make it default in the next major release.

**Comment by untitaker** [comment]
Opened a PR at #89, tests are a bit ugly but it works
