### ISSUE TITLE
Parallel reading

### ISSUE THREAD

**Issue by cblegare** [agronholm/sphinx-autodoc-typehints#9]
Got this warning from sphinx-build : 

```
WARNING: the sphinx_autodoc_typehints extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

So... is your extension safe for parallel reading ?

**Comment by agronholm** [comment]
I've never seen this before – does this come from from the latest Sphinx? I have no clue what parallel or serial reads mean in this context.

**Comment by abstrus** [comment]
The [code that issues this warning](https://github.com/sphinx-doc/sphinx/blame/70831a718ecd1604e73ee7ace535ff5332657a2b/sphinx/environment/__init__.py#L536) is tagged from 1.3 onwards. 

Based on a quick scan of the [changed files](https://github.com/sphinx-doc/sphinx/commit/31452fc64d550f526d3a6c4dfbb1121873896503), it looks like a an implementation for asynchrone I/O on source files that do not use [asyncio](https://docs.python.org/3/library/asyncio.html) or [trollius](https://pypi.python.org/pypi/trollius).

You can suppress this warning by returning a dictionary from the [ `setup()` function](https://github.com/agronholm/sphinx-autodoc-typehints/blob/master/sphinx_autodoc_typehints.py#L95). 

``` python
def setup(app):
    # do stuff with app
    return dict(
        version="unknown version",
        parallel_read_safe=False,
        parallel_write_safe=True
    )
```

You can read about it in the documentation about [extension metadata](http://www.sphinx-doc.org/en/1.4.8/extdev/index.html#extension-metadata).
