### ISSUE TITLE
Recursion errors with some recursive types

### ISSUE THREAD

**Issue by sangaline** [agronholm/sphinx-autodoc-typehints#91]
This type definition

```python
TreeType = typing.Dict[str, typing.Union['TreeType', typing.List['TreeType']]]
```

causes documentation generation to fail with the following recursion error.

```
Recursion error:
maximum recursion depth exceeded while calling a Python object
```

It appears that this only happens when the recursive type is referenced twice (*e.g* `TreeType = typing.Dict[str, 'TreeType']` works fine).

**Comment by agronholm** [comment]
Could you dig deeper into what is causing this?

**Comment by sangaline** [comment]
It happens in the `typing.get_type_hints()` call on [line 193](https://github.com/agronholm/sphinx-autodoc-typehints/blob/f4d43479e81ffc2a1562633176ecb9315716dd52/sphinx_autodoc_typehints.py#L193). There's an [upstream issue](https://github.com/python/typing/issues/574) that has been open for a year without any activity.

Could you possibly just patch

```python
    try:
        rv = get_type_hints(obj)
    except (AttributeError, TypeError):
        # Introspecting a slot wrapper will raise TypeError
        pass
```

to

```python
    try:
        rv = get_type_hints(obj)
    except (AttributeError, TypeError, RecursionError):
        # Introspecting a slot wrapper will raise TypeError
        pass
```

to ignore types that cause the error?

**Comment by agronholm** [comment]
It's an ugly workaround but I can't think of anything better.

**Comment by sangaline** [comment]
Agreed, but it seems like it's more of an upstream responsibility to fix the underlying issue. I put up #92 which at least allows builds to proceed without failure.
